
---
# training parameters
training_params:
  optimiser : optim.RMSprop
  weight_decay : 1e-6
  momentum : 0.9
  loss_function : nn.CrossEntropyLoss

# unet parameters
unet_params :
  kernel_size: 3
  padding: 1
  scale_factor: 2



